# Generated by Django 5.1.2 on 2024-11-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
